[build]
  publish = "dist/"
  command = "npm run generate"

[context.production]
  [context.production.environment]
    OAUTH_URL="https://staging.api.teams.wethos.co/oauth/token"
    API_URL_BASE="https://staging.api.teams.wethos.co/api/v1/"
    GRANT_TYPE="password"
    CLIENT_SECRET="vCtTyzGt3BX93HyQrixiIu4SSe0aa7veK9lWCefL"
    SCOPE="*"
    CLIENT_ID="2"